### ISSUE TITLE
Initial Boilerplate

### ISSUE THREAD

**Issue by russleyshaw** [kwiwk/test_plugin#1]
Things to add

- [x] CMakeLists.txt
- [x] .gitignore
- [x] main.cpp/bootstrapped main
- [x] folder for module code
- [ ] folder for bootstrapped code
- [x] travis.yml
- [x] Docker file

**Comment by JeremyDaug** [comment]
Added the CMakeLists.txt
.gitignore
main.cpp
folder for module code
yml file
and docker file
